---
name: release-branch
on:
  push:
    branches:
      - main
      - master/**
    paths-ignore:
      - '.github/**'
      - 'src/**'
      - 'test/**'

permissions:
  contents: write
  id-token: write

jobs:
  terraform-module:
    uses: nhanlh97/Nhanlh97-Mork-2023/.github/workflows/release-branch.yml@main
    secrets:
      github_access_token: ${{ secrets.REPO_ACCESS_TOKEN }}