---
name: release-published
on:
  release:
    types:
      - published

permissions:
  contents: write
  id-token: write

jobs:
  terraform-module:
    uses: /Users/nhanlh97/IdeaProjects/spring-thymeleaf/.github/workflows/release.yml@main