---
name: release-published
on:
  release:
    types:
      - published

permissions:
  contents: write
  id-token: write

jobs:
  terraform-module:
    uses: nhanlh97/Nhanlh97-Mork-2023/.github/workflows/release.yml@main